name: Github Actions CI

on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: 'Install dependencies'
              run: |
                  npm install
            - name: 'Display start of pipeline  '
              run: |
                  export TZ='Europe/Paris'
                  echo "Le pipeline débute à $(date +'%H:%M:%S %Z')"
            - name: 'Checking code'
              run: |
                  npm run prettier
            - name: 'Checking code with lint'
              run: |
                  npm run lint
            - name: 'Checking code with test coverage '
              run: |
                  npm run test:cover
            - name: 'building code with webPack'
              run: |
                  npm run build
            - name: 'Display ending of pipeline  '
              run: |
                  export TZ='Europe/Paris'
                  echo "Le pipeline débute à $(date +'%H:%M:%S %Z')"
            - name: 'Display pipeline success'
              run: |
                  echo "PIPELINE SUCCESS WITHOUT ERRORS"
